# Generated by Django 3.2.9 on 2021-12-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/noimagefound.png', null=True, upload_to='images'),
        ),
    ]
